// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package azwebex

import (
	"context"
	"reflect"

	resources "github.com/pulumi/pulumi-azure-native/sdk/go/azure/resources"
	storage "github.com/pulumi/pulumi-azure-native/sdk/go/azure/storage"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Webapp struct {
	pulumi.ResourceState

	Url pulumi.StringPtrOutput `pulumi:"url"`
}

// NewWebapp registers a new resource with the given unique name, arguments, and options.
func NewWebapp(ctx *pulumi.Context,
	name string, args *WebappArgs, opts ...pulumi.ResourceOption) (*Webapp, error) {
	if args == nil {
		args = &WebappArgs{}
	}

	if isZero(args.AppSkuName) {
		args.AppSkuName = pulumi.StringPtr("B1")
	}
	if isZero(args.AppSkuTier) {
		args.AppSkuTier = pulumi.StringPtr("Basic")
	}
	if isZero(args.FilePath) {
		args.FilePath = pulumi.StringPtr("wwwroot")
	}
	var resource Webapp
	err := ctx.RegisterRemoteComponentResource("azwebex:index:webapp", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type webappArgs struct {
	// The name of the compute instance running the server. Also see appSkuTier
	AppSkuName *string `pulumi:"appSkuName"`
	// The tier of the compute instance running the server. Also see appSkuName
	AppSkuTier *string `pulumi:"appSkuTier"`
	// The public access level of the BlobContainer containg the website data.
	ContainerPublicAccess *PublicAccess `pulumi:"containerPublicAccess"`
	// The relative file path to the folder containing web files.
	FilePath *string `pulumi:"filePath"`
	// The name prefix given to child resources of this component. Should not contain dashes.
	NamePrefix *string `pulumi:"namePrefix"`
	// The resource group to use. One will be created if not provided.
	ResourceGroup *resources.ResourceGroup `pulumi:"resourceGroup"`
	// The storage account to use. One will be created if not provided.
	StorageAccount *storage.StorageAccount `pulumi:"storageAccount"`
	// The name of the SKU of the storage account created, if storageAccount is not provided
	StorageSkuName *SkuName `pulumi:"storageSkuName"`
}

// The set of arguments for constructing a Webapp resource.
type WebappArgs struct {
	// The name of the compute instance running the server. Also see appSkuTier
	AppSkuName pulumi.StringPtrInput
	// The tier of the compute instance running the server. Also see appSkuName
	AppSkuTier pulumi.StringPtrInput
	// The public access level of the BlobContainer containg the website data.
	ContainerPublicAccess PublicAccessPtrInput
	// The relative file path to the folder containing web files.
	FilePath pulumi.StringPtrInput
	// The name prefix given to child resources of this component. Should not contain dashes.
	NamePrefix pulumi.StringPtrInput
	// The resource group to use. One will be created if not provided.
	ResourceGroup resources.ResourceGroupInput
	// The storage account to use. One will be created if not provided.
	StorageAccount storage.StorageAccountInput
	// The name of the SKU of the storage account created, if storageAccount is not provided
	StorageSkuName SkuNamePtrInput
}

func (WebappArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*webappArgs)(nil)).Elem()
}

type WebappInput interface {
	pulumi.Input

	ToWebappOutput() WebappOutput
	ToWebappOutputWithContext(ctx context.Context) WebappOutput
}

func (*Webapp) ElementType() reflect.Type {
	return reflect.TypeOf((**Webapp)(nil)).Elem()
}

func (i *Webapp) ToWebappOutput() WebappOutput {
	return i.ToWebappOutputWithContext(context.Background())
}

func (i *Webapp) ToWebappOutputWithContext(ctx context.Context) WebappOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WebappOutput)
}

type WebappOutput struct{ *pulumi.OutputState }

func (WebappOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Webapp)(nil)).Elem()
}

func (o WebappOutput) ToWebappOutput() WebappOutput {
	return o
}

func (o WebappOutput) ToWebappOutputWithContext(ctx context.Context) WebappOutput {
	return o
}

func (o WebappOutput) Url() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Webapp) pulumi.StringPtrOutput { return v.Url }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*WebappInput)(nil)).Elem(), &Webapp{})
	pulumi.RegisterOutputType(WebappOutput{})
}
