// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureJustrun
{
    [AzureJustrunResourceType("azure-justrun:index:containerapp")]
    public partial class Containerapp : Pulumi.ComponentResource
    {
        [Output("url")]
        public Output<string?> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Containerapp resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Containerapp(string name, ContainerappArgs args, ComponentResourceOptions? options = null)
            : base("azure-justrun:index:containerapp", name, args ?? new ContainerappArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ContainerappArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the docker image to use. Required.
        /// </summary>
        [Input("dockerImageName", required: true)]
        public Input<string> DockerImageName { get; set; } = null!;

        /// <summary>
        /// The name prefix given to child resources of this component. Should not contain dashes.
        /// </summary>
        [Input("namePrefix")]
        public Input<string>? NamePrefix { get; set; }

        /// <summary>
        /// The container registry to use. One will be created if not provided.
        /// </summary>
        [Input("registry")]
        public Input<Pulumi.AzureNative.ContainerRegistry.Registry>? Registry { get; set; }

        /// <summary>
        /// The resource group to use. One will be created if not provided.
        /// </summary>
        [Input("resourceGroup")]
        public Input<Pulumi.AzureNative.Resources.ResourceGroup>? ResourceGroup { get; set; }

        public ContainerappArgs()
        {
        }
    }
}
