// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureJustrun
{
    /// <summary>
    /// This represents a container app component resource
    /// </summary>
    [AzureJustrunResourceType("azure-justrun:index:containerapp")]
    public partial class Containerapp : Pulumi.ComponentResource
    {
        /// <summary>
        /// The URL of the container app
        /// </summary>
        [Output("url")]
        public Output<string?> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Containerapp resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Containerapp(string name, ContainerappArgs? args = null, ComponentResourceOptions? options = null)
            : base("azure-justrun:index:containerapp", name, args ?? new ContainerappArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ContainerappArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the docker image. One will be created if not provided
        /// </summary>
        [Input("dockerImageName")]
        public Input<string>? DockerImageName { get; set; }

        /// <summary>
        /// The name of the directory where the docker image to be created is. NOT the actual directory, i.e. 'nodeapp' instead of './nodeapp'
        /// </summary>
        [Input("imageDirectory")]
        public Input<string>? ImageDirectory { get; set; }

        /// <summary>
        /// The name prefix given to child resources of this component. Should not contain dashes.
        /// </summary>
        [Input("namePrefix")]
        public Input<string>? NamePrefix { get; set; }

        /// <summary>
        /// The name of the image registry. One will be created if not provided
        /// </summary>
        [Input("registryName")]
        public Input<string>? RegistryName { get; set; }

        /// <summary>
        /// The resource group to use. One will be created if not provided.
        /// </summary>
        [Input("resourceGroupName")]
        public Input<string>? ResourceGroupName { get; set; }

        /// <summary>
        /// The name of the storage account to use. One will be created if not provided.
        /// </summary>
        [Input("storageAccountName")]
        public Input<string>? StorageAccountName { get; set; }

        /// <summary>
        /// The version of the created docker image
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public ContainerappArgs()
        {
        }
    }
}
