// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.AzureJustrun
{
    [AzureJustrunResourceType("azure-justrun:index:webapp")]
    public partial class Webapp : Pulumi.ComponentResource
    {
        [Output("url")]
        public Output<string?> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Webapp resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Webapp(string name, WebappArgs? args = null, ComponentResourceOptions? options = null)
            : base("azure-justrun:index:webapp", name, args ?? new WebappArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class WebappArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the compute instance running the server. Also see appSkuTier
        /// </summary>
        [Input("appSkuName")]
        public Input<string>? AppSkuName { get; set; }

        /// <summary>
        /// The tier of the compute instance running the server. Also see appSkuName
        /// </summary>
        [Input("appSkuTier")]
        public Input<string>? AppSkuTier { get; set; }

        /// <summary>
        /// The public access level of the BlobContainer containg the website data.
        /// </summary>
        [Input("containerPublicAccess")]
        public Input<Pulumi.AzureJustrun.PublicAccess>? ContainerPublicAccess { get; set; }

        /// <summary>
        /// The relative file path to the folder containing web files.
        /// </summary>
        [Input("filePath")]
        public Input<string>? FilePath { get; set; }

        /// <summary>
        /// The name prefix given to child resources of this component. Should not contain dashes.
        /// </summary>
        [Input("namePrefix")]
        public Input<string>? NamePrefix { get; set; }

        /// <summary>
        /// The resource group to use. One will be created if not provided.
        /// </summary>
        [Input("resourceGroup")]
        public Input<Pulumi.AzureNative.Resources.ResourceGroup>? ResourceGroup { get; set; }

        /// <summary>
        /// The storage account to use. One will be created if not provided.
        /// </summary>
        [Input("storageAccount")]
        public Input<Pulumi.AzureNative.Storage.StorageAccount>? StorageAccount { get; set; }

        /// <summary>
        /// The name of the SKU of the storage account created, if storageAccount is not provided
        /// </summary>
        [Input("storageSkuName")]
        public Input<Pulumi.AzureJustrun.SkuName>? StorageSkuName { get; set; }

        public WebappArgs()
        {
            AppSkuName = "B1";
            AppSkuTier = "Basic";
            FilePath = "wwwroot";
        }
    }
}
