// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const PublicAccess = {
    Container: "Container",
    Blob: "Blob",
    None: "None",
} as const;

/**
 * Specifies whether data in the container may be accessed publicly and the level of access.
 */
export type PublicAccess = (typeof PublicAccess)[keyof typeof PublicAccess];

export const StorageSkuName = {
    Standard_LRS: "Standard_LRS",
    Standard_GRS: "Standard_GRS",
    Standard_RAGRS: "Standard_RAGRS",
    Standard_ZRS: "Standard_ZRS",
    Premium_LRS: "Premium_LRS",
    Premium_ZRS: "Premium_ZRS",
    Standard_GZRS: "Standard_GZRS",
    Standard_RAGZRS: "Standard_RAGZRS",
} as const;

/**
 * The SKU name. Required for account creation; optional for update. Note that in older versions, SKU name was called accountType.
 */
export type StorageSkuName = (typeof StorageSkuName)[keyof typeof StorageSkuName];
