# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .static_website import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "azwebex",
  "mod": "index",
  "fqn": "pulumi_azwebex",
  "classes": {
   "azwebex:index:staticWebsite": "StaticWebsite"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "azwebex",
  "token": "pulumi:providers:azwebex",
  "fqn": "pulumi_azwebex",
  "class": "Provider"
 }
]
"""
)
