// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package azurejustrun

type SampleType struct {
	Age  *int    `pulumi:"age"`
	Name *string `pulumi:"name"`
}

func init() {
}
